site_name: Heimdall Hub
repo_url: null
theme:
  name: material
nav:
  - Home: index.md
  - Projects: projects.md
  - Now: now.md
  - Inbox: inbox.md
  - Reference: reference.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
